/**
 * Do not edit directly
 * Generated on Fri, 23 Jun 2023 16:10:38 GMT
 */

export const globalColorsFoundationBrandPrimary = "#f2d462"; // brand_p600
export const globalColorsFoundationBlack = "#000000";
export const globalColorsFoundationWhite = "#ffffff";
export const globalColorsBrandPrimaryBrandP700 = "#42370c"; // #B1025D
export const globalColorsBrandPrimaryBrandP600 = "#6d5a1a"; // #C40065
export const globalColorsBrandPrimaryBrandP500 = "#99802b"; // #E20177
export const globalColorsBrandPrimaryBrandP400 = "#c5a83f"; // #E83492
export const globalColorsBrandPrimaryBrandP300 = "#f2d462"; // #EE67AD
export const globalColorsBrandPrimaryBrandP200 = "#fcefa0"; // #F399C9
export const globalColorsBrandPrimaryBrandP100 = "#fdf4c7"; // #F6B3D6
export const globalColorsBrandPrimaryBrandP50 = "#fefbee"; // #FCE6F1
export const globalColorsNeutralGray900 = "#141414"; // #141414
export const globalColorsNeutralGray800 = "#1f1f1f"; // #1F1F1F
export const globalColorsNeutralGray700 = "#333333"; // #333333
export const globalColorsNeutralGray600 = "#545454"; // #545454
export const globalColorsNeutralGray500 = "#757575"; // #757575
export const globalColorsNeutralGray400 = "#afafaf"; // #AFAFAF
export const globalColorsNeutralGray300 = "#cbcbcb"; // #CBCBCB
export const globalColorsNeutralGray200 = "#e2e2e2"; // #E2E2E2
export const globalColorsNeutralGray100 = "#eeeeee"; // #EEEEEE
export const globalColorsNeutralGray50 = "#f6f6f6"; // #F6F6F6
export const globalColorsSemanticGreenGreen700 = "#063d1b";
export const globalColorsSemanticGreenGreen600 = "#0a3f1a";
export const globalColorsSemanticGreenGreen500 = "#124c1c";
export const globalColorsSemanticGreenGreen400 = "#277227";
export const globalColorsSemanticGreenGreen300 = "#6fb557";
export const globalColorsSemanticGreenGreen200 = "#b6e188";
export const globalColorsSemanticGreenGreen100 = "#d5f6ad";
export const globalColorsSemanticGreenGreen50 = "#ebfcd5";
export const globalColorsSemanticRedRed700 = "#5c1d16";
export const globalColorsSemanticRedRed600 = "#892c21";
export const globalColorsSemanticRedRed500 = "#ae372a";
export const globalColorsSemanticRedRed400 = "#d44333";
export const globalColorsSemanticRedRed300 = "#eb7567";
export const globalColorsSemanticRedRed200 = "#f4afa7";
export const globalColorsSemanticRedRed100 = "#fadbd7";
export const globalColorsSemanticRedRed50 = "#fdf0ef";
export const globalColorsCoreContentPrimary = "#000000";
export const globalColorsCoreContentSecondary = "#545454";
export const globalColorsCoreContentTertiary = "#757575";
export const globalColorsCoreContentInversePrimary = "#ffffff";
export const globalColorsCoreContentInverseSecondary = "#afafaf";
export const globalColorsCoreContentInverseTertiary = "#e2e2e2";
export const globalColorsCoreBorderPrimary = "#d9d9d9"; // #D9D9D9
export const globalColorsCoreBorderHover = "#141414"; // #141414
export const globalColorsCoreBorderSelected = "#09c3ec"; // #09C3EC
export const globalColorsCoreBorderInversePrimary = "#ffffff";
export const globalColorsCoreBorderInverseHover = "#afafaf";
export const globalColorsCoreBorderInverseSelected = "#09c3ec";
export const globalColorsCoreBackgroundPrimary = "#ffffff"; // #FFFFFF
export const globalColorsCoreBackgroundSecondary = "#f6f6f6"; // #F6F6F6
export const globalColorsCoreBackgroundTertiary = "#eeeeee"; // #EEEEEE
export const globalColorsCoreBackgroundInversePrimary = "#000000";
export const globalColorsCoreBackgroundInverseSecondary = "#1f1f1f";
export const globalColorsCoreBackgroundInverseTertiary = "#141414";
export const globalColorsCoreUtilityNegative = "#d44333"; // #D44333
export const globalColorsCoreUtilityWarning = "#e4b725"; // #E4B725
export const globalColorsCoreUtilityPositive = "#277227"; // #277227
export const globalColorsCoreUtilityInverseNegative = "#eb7567";
export const globalColorsCoreUtilityInverseWarning = "#f9db4a";
export const globalColorsCoreUtilityInversePositive = "#6fb557";
export const globalColorsCoreTintsBrandPrimary = "#fefbee";
export const globalColorsCoreTintsBrandSecondary = "#eef7ff"; // #EEF7FF
export const globalColorsCoreTintsNegartive = "#fdf0ef"; // #FDF0EF
export const globalColorsCoreTintsWarning = "#fff1c0"; // #FFF1C0
export const globalColorsCoreTintsPositive = "#ebfcd5"; // #EBFCD5
export const globalColorsCoreTintsInverseBrandPrimary = "#f6b3d6";
export const globalColorsCoreTintsInverseBrandSecondary = "#d0e9ff";
export const globalColorsCoreTintsInverseNegative = "#fadbd7";
export const globalColorsCoreTintsInverseWarning = "#ffeb92";
export const globalColorsCoreTintsInversePositive = "#d5f6ad";
export const globalColorsCoreOverlayDark = "#0000004d"; // Light background overlays
export const globalColorsCoreOverlayLight = "#00000014"; // Light background overlays
export const globalColorsCoreOverlayInverseLight = "#ffffff14"; // Dark background overlays
export const globalColorsCoreOverlayInverseDark = "#ffffff4d"; // Dark background overlays
export const globalHandset = "8px"; // Small 
export const globalTablet = "12px";
export const globalDesktop = "16px";
export const global12px = "12px";
export const global14px = "14px";
export const global16px = "16px";
export const global52px = "52px";
export const global20px = "20px";
export const global24px = "24px";
export const global28px = "28px";
export const global32px = "32px";
export const global36px = "36px";
export const global40px = "40px";
export const global44px = "44px";
export const global64px = "64px";
export const global112px = "112px";
export const fontFamiliesPrimaryFont = "Montserrat";
export const lineHeights12px = "12px";
export const lineHeights14px = "14px";
export const lineHeights16px = "16px";
export const lineHeights20px = "20px";
export const lineHeights24px = "24px";
export const lineHeights28px = "28px";
export const lineHeights32px = "32px";
export const lineHeights36px = "36px";
export const lineHeights52px = "52px";
export const lineHeights40px = "40px";
export const lineHeights44px = "44px";
export const lineHeights64px = "64px";
export const lineHeights112px = "112px";
export const lineHeightsAuto = "AUTO";
export const fontWeightsBold = "700";
export const fontWeightsMedium = "500";
export const fontWeightsRegular = "400";
export const fontWeightsItalic = "Italic";
export const fontSize10px = "10px";
export const fontSize12px = "12px";
export const fontSize14px = "14px";
export const fontSize16px = "16px";
export const fontSize18px = "18px";
export const fontSize20px = "20px";
export const fontSize24px = "24px";
export const fontSize28px = "28px";
export const fontSize32px = "32px";
export const fontSize36px = "36px";
export const fontSize40px = "40px";
export const fontSize44px = "44px";
export const fontSize52px = "52px";
export const fontSize96px = "96px";
export const letterSpacing0 = "0";
export const paragraphSpacing0 = "0";
export const xxLargeHeading = "700 40px/52px Montserrat";
export const xLargeHeading = "700 36px/44px Montserrat";
export const largeDisplay = "700 96px/112px Montserrat";
export const largeHeading = "700 32px/40px Montserrat";
export const largeLabel = "500 18px/24px Montserrat";
export const largeParagraph = "400 18px/28px Montserrat"; // Regular 400
export const mediumDisplay = "700 52px/64px Montserrat";
export const mediumHeading = "700 28px/36px Montserrat";
export const mediumLabel = "500 16px/20px Montserrat";
export const mediumParagraph = "400 16px/24px Montserrat";
export const smallDisplay = "700 44px/52px Montserrat";
export const smallHeading = "700 24px/32px Montserrat";
export const smallLabel = "500 14px/16px Montserrat";
export const smallParagraph = "400 14px/20px Montserrat";
export const xxSmallLabel = "500 10px/12px Montserrat";
export const xxSmallParagraph = "400 10px/14px Montserrat";
export const xxSmallItalic = "Italic 10px/14px Montserrat";
export const xSmallDisplay = "700 36px/44px Montserrat";
export const xSmallHeading = "700 20px/28px Montserrat";
export const xSmallLabel = "500 12px/14px Montserrat";
export const xSmallParagraph = "400 12px/AUTO Montserrat";
export const textCaseNone = "none";
export const textDecorationNone = "none";
export const paragraphIndent0 = "0px";
